output: main.o GTUSet.o GTUVector.o
	g++ main.o GTUSet.o GTUVector.o -o output

GTUVector.o: GTUVector.cpp
	g++ -c GTUVector.cpp -std=c++11

GTUSet.o: GTUSet.cpp
	g++ -c GTUSet.cpp -std=c++11

main.o: main.cpp
	g++ -c main.cpp	-std=c++11
